#http://ohmyz.sh/
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="daveverwer"
source $ZSH/oh-my-zsh.sh

# self config
plugins=(git python golang history history-substring-search macports pip redis-cli rsync svn tmux vi-mode fabric autojump brew osx)


#保存历史
export HISTSIZE=20000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE
#忽略重复
setopt hist_ignore_all_dups

# Customize to your needs...
export PATH=$PATH:/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/bin:/opt/local/sbin:/Users/ken/bin:/usr/local/git/bin

# andriod path
export PATH=${PATH}:/Users/xuanxiao/Developer/adt-bundle-mac-x86_64-20131030/sdk/platform-tools:/Users/xuanxiao/Developer/adt-bundle-mac-x86_64-20131030/sdk/tools
export PATH=${PATH}:/Users/xuanxiao/Applications/apache-ant-1.9.4/bin/

# 输入文件名即可打开
alias -s py=vi
alias -s js=vi
alias -s c=vi
alias -s java=vi
alias -s txt=vi
#alias -s sh=vi
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'

# auto update
DISABLE_UPDATE_PROMPT=true


#OS_CONFIG_DIR=$(cd "$(dirname '$0')"; pwd)
OS_CONFIG_DIR="$HOME/.osconfig"
source $OS_CONFIG_DIR/bash_profile
source $OS_CONFIG_DIR/aliases/bash_aliases
source $OS_CONFIG_DIR/aliases/git_aliases
source $OS_CONFIG_DIR/aliases/svn_aliases
source $OS_CONFIG_DIR/aliases/own_aliases
